# Generated by Django 3.1.3 on 2020-12-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('countryName', models.CharField(max_length=100, unique=True)),
                ('coronaPositive', models.CharField(max_length=100)),
                ('death', models.CharField(max_length=100)),
            ],
        ),
    ]
