# Generated by Django 3.1.3 on 2020-12-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='coronaPositive',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='death',
            field=models.IntegerField(),
        ),
    ]
